FROM node:20.18.3-alpine3.21
RUN addgroup --system expense && adduser --system --ingroup expense expense && \
     mkdir /opt/backend && \
    chown -R expense:expense /opt/backend && \
WORKDIR /opt/backend
    

